# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            isena
tagline:          Mobile First
url:              http://isena.github.io/
paginate:         1
baseurl:          /
author:
  name:           Isaac Stevao Sena
  url:            https://br.linkedin.com/in/isaacsena
  email:          isaac.sena@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/isena
